/**
 * ChartTooltip
 *
 * Renders a lightweight custom HTML tooltip above the chart.
 *
 * Why this component exists:
 * - Lightweight Charts does not provide a fully styled React-native tooltip UI
 * - the chart interaction layer only exposes the tooltip state and positioning
 * - this component is responsible solely for presenting that state
 *
 * Architectural notes:
 * - rendering is conditional to avoid unnecessary DOM nodes when the tooltip
 *   is not visible
 * - positioning is driven externally by chart interaction logic
 * - the component stays intentionally simple and stateless so that tooltip
 *   display concerns remain decoupled from crosshair event handling
 *
 * @param {Object} props
 * @param {Object} props.tooltip Tooltip view model generated by chart interaction logic.
 * @param {boolean} props.tooltip.visible Whether the tooltip should currently be displayed.
 * @param {number} props.tooltip.left Horizontal offset relative to the chart container.
 * @param {number} props.tooltip.top Vertical offset relative to the chart container.
 * @param {string} props.tooltip.date Formatted date/time label for the hovered point.
 * @param {string} props.tooltip.price Formatted main series value.
 * @param {string} [props.tooltip.sma] Optional formatted SMA value.
 * @param {string} [props.tooltip.ema] Optional formatted EMA value.
 * @returns {JSX.Element | null}
 */

import React from "react";

export default function ChartTooltip({ tooltip }) {
  if (!tooltip.visible) {
    return null;
  }

  return (
    <div
      style={{
        position: "absolute",
        left: tooltip.left,
        top: tooltip.top,
        minWidth: 180,
        padding: 12,
        borderRadius: 10,
        background: "rgba(0,0,0,0.85)",
        color: "#fff",
        fontSize: 12,
        pointerEvents: "none",
        zIndex: 10,
      }}
    >
      <div style={{ fontWeight: 700, marginBottom: 6 }}>{tooltip.date}</div>
      <div>Price: {tooltip.price}</div>
      {tooltip.sma && <div>SMA: {tooltip.sma}</div>}
      {tooltip.ema && <div>EMA: {tooltip.ema}</div>}
    </div>
  );
}
